version: '3'
services:
    mongo:
      image: "mongo-start"
      build: ./mongo
      ports:
        - "27017:27017"
      volumes:
        - ./mongo/data:/data/db
      deploy:
        replicas: 1
        update_config:
          parallelism: 2
          delay: 10s
        restart_policy:
          condition: on-failure
    portainer:
      image: "portainer"
      build: ./portainer
      ports:
        - "9000:9000"
      deploy:
        update_config:
          delay: 10s