version: '3'
services:
    mongo:
      image: "mongo-start"
      build: ./mongo
      ports:
        - "27017:27017"
      volumes:
        - ./mongo/data:/data/db
      deploy:
        replicas: 1
        update_config:
          parallelism: 2
          delay: 10s
        restart_policy:
          condition: on-failure
          
    setup-rs:
      image: "setup-rs"
      build: ./setup
      depends_on:
        - "mongo"

    adminmongo:
      image: "mrvautin/adminmongo"
      ports:
        - "1234:1234"

    arbiter:
      image: "mongo-start"
      build: ./arbiter
      ports:
        - "30000:30000" 
